
import javax.swing.JOptionPane;

/**
 *
 * @author Adm
 */
public class cadastroVIEW extends javax.swing.JFrame {

    /**
     * Creates new form cadastroVIEW
     */
    public cadastroVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_sistemaDeLeiloes = new javax.swing.JLabel();
        Lbl_cadastreProduto = new javax.swing.JLabel();
        Lbl_nomeProduto = new javax.swing.JLabel();
        Lbl_valorProduto = new javax.swing.JLabel();
        Txt_cadastroNome = new javax.swing.JTextField();
        Txt_cadastroValor = new javax.swing.JTextField();
        separadorSuperior = new javax.swing.JSeparator();
        separadorInferior = new javax.swing.JSeparator();
        btn_Cadastrar = new javax.swing.JButton();
        btn_ConsultarProdutos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_sistemaDeLeiloes.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        Lbl_sistemaDeLeiloes.setText("Sistema de Leilões");

        Lbl_cadastreProduto.setText("Cadastre um novo produto");

        Lbl_nomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lbl_nomeProduto.setText("Nome:");

        Lbl_valorProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lbl_valorProduto.setText("Valor:");

        Txt_cadastroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_cadastroNomeActionPerformed(evt);
            }
        });

        btn_Cadastrar.setBackground(new java.awt.Color(153, 255, 255));
        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_ConsultarProdutos.setText("Consultar Produtos");
        btn_ConsultarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btn_Cadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Lbl_sistemaDeLeiloes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ConsultarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(202, 202, 202)
                            .addComponent(Lbl_cadastreProduto))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lbl_nomeProduto)
                                .addComponent(Lbl_valorProduto))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Txt_cadastroNome)
                                .addComponent(Txt_cadastroValor, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(separadorInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Lbl_sistemaDeLeiloes)
                .addGap(30, 30, 30)
                .addComponent(separadorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_cadastreProduto)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nomeProduto)
                    .addComponent(Txt_cadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_valorProduto)
                    .addComponent(Txt_cadastroValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_Cadastrar)
                .addGap(18, 18, 18)
                .addComponent(separadorInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btn_ConsultarProdutos)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_cadastroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_cadastroNomeActionPerformed
        
        
    }//GEN-LAST:event_Txt_cadastroNomeActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        
        if (camposVazios() == false){//Todos os campos foram preenchidos
            //Criando o produto inserido
            ProdutosDTO produto = new ProdutosDTO();
            String nome = Txt_cadastroNome.getText();
            String valor = Txt_cadastroValor.getText().trim();
//            String status = "A Venda";
            produto.setNome(nome);
            produto.setValor(Integer.valueOf(valor));
//            produto.setStatus(status);

            //Passando o produto inserio no banco de dados
            ProdutosDAO produtodao = new ProdutosDAO();
            
            if(produtodao.cadastrarProduto(produto) == 1){//Cadastro feito
                JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao cadastrar o produto, contate o administrador");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        }
        
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_ConsultarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarProdutosActionPerformed
        listagemVIEW listagem = new listagemVIEW(this); 
        listagem.setVisible(true);
    }//GEN-LAST:event_btn_ConsultarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_cadastreProduto;
    private javax.swing.JLabel Lbl_nomeProduto;
    private javax.swing.JLabel Lbl_sistemaDeLeiloes;
    private javax.swing.JLabel Lbl_valorProduto;
    private javax.swing.JTextField Txt_cadastroNome;
    private javax.swing.JTextField Txt_cadastroValor;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_ConsultarProdutos;
    private javax.swing.JSeparator separadorInferior;
    private javax.swing.JSeparator separadorSuperior;
    // End of variables declaration//GEN-END:variables


    public boolean camposVazios(){
        boolean vazios = false; //Os campos estão preenchidos
        
        if(Txt_cadastroNome.getText().isEmpty() ||
           Txt_cadastroValor.getText().isEmpty()){
            vazios = true;
            }
    
        return vazios;
    }
}
